### ISSUE TITLE
node:internal/modules/cjs/loader:940  Error: Cannot find module 'react-scripts/package.json'

### ISSUE THREAD

**Issue by Jansora** [sql-js/react-sqljs-demo#5]
1. download source code `git clone https://github.com/sql-js/react-sqljs-demo.git`
2. `cd https://github.com/sql-js/react-sqljs-demo.git`
3. install dependencies `yarn`
4. yarn start. A error has reached.
```
➜  react-sqljs-demo git:(master) ✗ yarn start
yarn run v1.22.10
$ craco start
node:internal/modules/cjs/loader:940
  const err = new Error(message);
              ^

Error: Cannot find module 'react-scripts/package.json'
Require stack:
- /Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/lib/cra.js
- /Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/scripts/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at resolvePackageJson (/Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/lib/cra.js:42:20)
    at getReactScriptVersion (/Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/lib/cra.js:46:40)
    at validateCraVersion (/Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/lib/validate-cra-version.js:4:38)
    at /Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/scripts/start.js:23:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/lib/cra.js',
    '/Users/jansora/Documents/Github/react-sqljs-demo/node_modules/@craco/craco/scripts/start.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Jansora** [comment]
MacOS 11.0.1
Chrome 93.0.4577.63

**Comment by Jansora** [comment]
I has solved it by adding dependency `react-scripts`
1. `yarn add react-scripts`
2. `yarn start`
